service: url-shortener

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    TABLE_NAME: UrlMappings
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/UrlMappings

functions:
  shortenUrl:
    handler: handler.shorten_url
    events:
      - http:
          path: shorten
          method: post
          cors: true

  redirectUrl:
    handler: redirect.redirect_url
    events:
      - http:
          path: /{shortCode}
          method: get
          cors: true

resources:
  Resources:
    UrlMappings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UrlMappings
        AttributeDefinitions:
          - AttributeName: shortCode
            AttributeType: S
        KeySchema:
          - AttributeName: shortCode
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
